deepcharles/ruptures

- ruptures/show/display.py
Pandas dataframes work like Numpy arrays in many instances, but can't be iterated through in the same way. This simply uses the underlying array when passed a dataframe instead of an array.
> Try to use pandas dataframe as array when passed non-array

- ruptures/show/display.py
- setup.py
- tests/test_display.py
Hi,
Matplotlib is sometimes hard to install in server and headless setups.
Since it's not required to use the main part of the library, I think it makes sense to make it optional.
I'm open to suggestions if there is a better way to implement this functionality.
In the meantime, I've pushed the fork to pypi as [ruptures-headless](https://pypi.org/project/ruptures-headless/) but I'd be happy to not maintain a fork :)
> Make matplotlib an optional dependency

- ruptures/costs/costrbf.py
During some different tests, we experiment a weird behaviour with PELT (RBF cost function) 
When median(K) is equal to 0, the  segmentation is clearly weird : each segment have an equal length (5).
To experiment this you can run the following code 
```python
import ruptures
import numpy as np
curve= [0, 528, 503, 0, 0, 0, 541, 542, 0, 542, 0, 0, 0, 542, 
500, 530, 0, 0, 515, 0, 536, 0, 0, 539, 518, 0, 0, 530, 0, 0, 
503, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0]
curve = np.array(curve)
algo = ruptures.Pelt(model='rbf', min_size=1).fit(curve)
seg = algo.predict(pen=1)
ruptures.display(curve, seg)
```
Which leads to this segmentation : 
We basically corrected this error by not dividing if the median is 0.
We are not sure about what this correction implies …
> Weird behaviour correction when median(K) = 0

- ruptures/detection/bottomup.py
- ruptures/utils/bnode.py
* Maintain merge candidates in a heap/priority queue
* Use binary search to maintain a sorted list of leaves instead of rebuilding it each iteration
For a large input array, I found this to be about 5-6x faster than the current implementation for the `predict` step.  
It is somewhat more complicated, and could be implemented in a cleaner manner (e.g., create an actual priority queue class, or use some of the ideas presented in the [heapq documentation](https://docs.python.org/3/library/heapq.html#priority-queue-implementation-notes)). 
Both of these ideas would be a bit of work (that I don't have time for right now), and, depending on the choices made, could limit compatible versions of python (e.g., if data classes were used).
But I would be happy if @deepcharles or someone else used …
> Speed up BottomUp algorithm

- README.md
This temporary link is to be used until the definitive documentation website is decided.
> Add a temporary link to the documentation

- .github/workflows/publish-doc-to-remote.yml
Only push the `build/html/` to the remote repo
> Better doc publishing process

- ruptures/detection/window.py
Correction of the description of predict function, fixes #59
> doc, Window-based change point detection

- .circleci/config.yml
- .github/workflows/check-docs.yml
- .github/workflows/publish-doc-to-remote.yml
- .github/workflows/run-test.yml
- CONTRIBUTING.md
- setup.cfg
- setup.py
And automage build_ext --inplace
> build(setup.py/cfg): add necessary files to sdist for build 

- ruptures/detection/_detection/ekcpd_computation.c
- ruptures/detection/_detection/ekcpd_pelt_computation.c
- ruptures/utils/_utils/convert_path_matrix_c.c
- An allocated array was not freed in `ekcpd_pelt_computation.c`
- code cleaning
> fix: fix memory leak in KernelCPD

- ruptures/detection/_detection/ekcpd_pelt_computation.c
The first segment was not respecting the `min_size` requirement.
Now results are consistent with Python version of `pelt`.
> fix(kernelcpd): bug fix in pelt

- .github/labeler.yml
- .github/release-drafter.yml
- .github/workflows/lint-pr.yml
- .github/workflows/pr-labeler.yml
- .github/workflows/release-drafter.yml
Three github actions are added:
- `lint-pr.yml`: verify that a pr follows the conventional commit conventions (https://github.com/amannn/action-semantic-pull-request).
- `pr-labeler.yml`: add label to PR by reading its title (https://github.com/jimschubert/labeler-action)
- `release-drafter.yml`: build a release draft for each new PR that is merged with the `main` branch (https://github.com/release-drafter/release-drafter)
> ci: add gh actions for PR labeling

- src/ruptures/detection/kernelcpd.py
- tests/test_detection.py
Fix proposal for [this](https://github.com/deepcharles/ruptures/issues/110) issue
> fix(KernelCPD): explicitly cast signal into double

- pyproject.toml
In pyproject.toml. This way, the oldest numpy version is better managed.
Closes #113
> build: use oldest-supported-numpy

- .github/workflows/upload-to-pypi.yml
Use `joerick/cibuildwheel@v1.9.0` in gh action that uploads to pypi.
Maybe this will solve the problem of the `SETUPTOOLS_SCM_PRETEND_VERSION` variable not seen on `manylinux1` (by default cibuildwheel uses `manylinux2010`.
> ci: use joerick/cibuildwheel@v1.9.0 action in upload to pypi

- .github/workflows/check-docs.yml
- .github/workflows/publish-doc-to-remote.yml
- docs/examples/music-segmentation.ipynb
A notebook example needs librosa and librosa needs a library that cannot be installed with `pip` (see [here](https://pysoundfile.readthedocs.io/en/latest/#installation)).
We add the dependency to the gh actions that generate the docs.
> ci: add depency for librosa

- .github/workflows/run-test.yml
We recently have a problem to run the test within the CI with GH Actions. 
See stackoverflow question for more detail : https://stackoverflow.com/questions/67296563/github-actions-stays-stuck-on-a-task-and-finally-fail-on-timeout
Following the [comment](https://stackoverflow.com/questions/67296563/github-actions-stays-stuck-on-a-task-and-finally-fail-on-timeout?noredirect=1#comment118990125_67296563) on the stackoverflow issue, I tried in [run-test.yml](https://github.com/deepcharles/ruptures/blob/master/.github/workflows/run-test.yml) not to upgrade `pip`. It did partially the job since more runs completed. But at the end, it stayed stuck. See [here](https://github.com/deepcharles/ruptures/actions/runs/798695169) to see the run. 
I investigated the following message in the CI : 
``` …
```
> chore: set manually a working version of pip for install

- src/ruptures/costs/costautoregressive.py
closes https://github.com/deepcharles/ruptures/issues/162
> fix: enfoce deepcopy for costar to avoid inplace modifications

- setup.cfg
Solves https://github.com/deepcharles/ruptures/pull/167/checks?check_run_id=2769725773
> build: add nltk dependency to run docs examples

- src/ruptures/show/display.py
- tests/test_display.py
Firstly thanks for a cool library.  The following proposed change is cosmetic only.
The current `display` plot of the `computed_chg_pts` renders the dashed vertical dashed lines with `linewidth=3` and no alpha.  This results in the dashed vertical lines overlaying the signal and obscuring it.
```
rpt.display(signal, results, computed_chg_pts, figsize=(8, 4))
```
**Please note**  these example plots are **not broken**, they are using a modified `results` list with only results from a specific window plotted, they are just highlighting a specific change point in a defined period, hence no leading change points or trailing change points are plotted.
The proposed change allows the user to pass additional arguments that allow the user to format the `computed_chg_pts` axvline parameters to …
> feat(display): more display options

- .github/labeler.yml
- setup.cfg
- src/ruptures/show/display.py
- tests/test_display.py
thanks to this PR, PRs initiated by pre-commit autoupdate will not be part of the changelog (tagged as "skip-changelog")
> chore: better PR labeler

- src/ruptures/detection/binseg.py
- src/ruptures/detection/bottomup.py
- src/ruptures/detection/dynp.py
- tests/test_detection.py
Hi!
I tried to use `copy.deepcopy` to copy `Binseg` object and met a problem: `binseg.single_bkp` and `deepcopy(binseg).single_bkp` referred to the same object. So, I can not use `binseg_copy.single_bkp` because it tries to use the data from the original object.
It seems to be caused by the way `lru_cache` is used. Are there any reasons not to use it with `@` decorator syntax?
> fix: lru-cache usage

- .github/workflows/upload-to-pypi.yml
Added aarch64 wheel build support.
Related to https://github.com/deepcharles/ruptures/issues/179, @julia-shenshina Could you please review this PR?
> build: add aarch64 wheel build support

- .github/workflows/check-docs.yml
- .github/workflows/run-test-coverage.yml
- .github/workflows/run-test.yml
The situation : 
As of today, for the PRs automatically generated by `pre-commit-ci` from branch `pre-commit-ci-update-config` to `master` and only affecting `.pre-commit-config.yaml`, run all the CI tests like any other PRs. 
What we do :
When only `.pre-commit-config.yaml` is affected by the PR, then the following Gh Actions are not run :
> ci: do not triggers some gh actions for pre-commit-ci-update-config branch

- .github/workflows/run-test.yml
Since the coverage is computed in `.github/workflows/run-test-coverage.yml`, we do not need to compute code coverage when we run the tests with `.github/workflows/run-test.yml`.
Moreover (and this is the main reason for the current PR), adding the `--no-cov` option make the tests run **way** faster ! Since we run those tests on a matrix on `python-version` x `os`, it might be a significant improvement for the time needed in the CI to run the tests !
> test: remove coverage computation from test

- src/ruptures/detection/binseg.py
- src/ruptures/detection/bottomup.py
- src/ruptures/detection/kernelcpd.py
- src/ruptures/detection/pelt.py
- src/ruptures/detection/window.py
- tests/test_detection.py
In cases where the `n_bkps` is not explicitly specified, current `sanity_check()` usage does not reflect how it should be used. Indeed, in some cases, finding 0 `n_bkps` is a fine results. Therefore, we should not make the assumption that there is at least 1 break point in the following cases : 
* `Binseg` : if the `n_bkps` is not specified at `predict()` time, then allow for 0 break points
* `BottomUp` : if the `n_bkps` is not specified at `predict()` time, then allow for 0 break points
* `Window` : if the `n_bkps` is not specified at `predict()` time, then allow for 0 break points
* `Pelt` : allow for 0 break points
There is one special case : 
* `KernelCPD` : our C implementation make the assumption that when it is called, we are looking for at least 1 break point. Therefore, for this …
> fix: sanity_check usage when n_bkps is not explicitly specified

- .flake8
- setup.py
- src/ruptures/datasets/pw_linear.py
- src/ruptures/detection/kernelcpd.py
- src/ruptures/metrics/hamming.py
- src/ruptures/metrics/precisionrecall.py
- src/ruptures/utils/__init__.py
- src/ruptures/utils/utils.py
- tests/test_datasets.py
- tests/test_metrics.py
Just add the F401 flake8 code to `.flake8` so that we have a warning message when there is an unused import. 
For instance in `src/ruptures/utils/utils.py` [here](https://github.com/deepcharles/ruptures/blob/d211c5c6257722aefafa81499a3171f1bf42a6a7/src/ruptures/utils/utils.py#L7) with `numpy`.
> style: add module imported but unused in flake8

- .github/workflows/run-test.yml
Some tests do not complete and time out. 
We started noting this behaviour in https://github.com/deepcharles/ruptures/pull/198
Tests are fine for python v3.8 and v3.9. Nevertheless, for v3.6 and v3.7, jobs stay stuck on the `python -m pip install .[test]` instruction. 
Previously, a specific pip version was enforced because at that time there was also some GH Actions jobs that stayed stuck. See https://github.com/deepcharles/ruptures/pull/153
> ci(gh-tests): change pip version for test jobs

- .github/workflows/run-test-coverage.yml
- .github/workflows/run-test.yml
Prevent the two following GH Actions to run when only documentation is modified : 
* `ruptures/.github/workflows/run-test.yml`
* `ruptures/.github/workflows/run-test-coverage.yml`
> ci: do not run tests when only documentation is modified

- src/ruptures/costs/costml.py
- tests/test_costs.py
When called  twice `CostMl.fit` does not recompute the `CostMl.metric` matrix. For instance the following code fails.
```python
import ruptures as rpt
c = rpt.costs.CostMl()
signal_1D, _ = rpt.pw_constant(n_features=1)
signal_5D, _ = rpt.pw_constant(n_features=5)
c.fit(signal_1D)
c.fit(signal_5D)
```
This is because the second call of `.fit()` does not recompute the metric matrix as it should. Array dimensions become incoherent. 
**Expected behaviour.** On the second call of `.fit()`, the Mahalanobis metric matrix should be recomputed and no error should be raised. However if the user provided a metric matrix, it should be used in priority and no new computation is needed.
> fix: CostMl fitting behaviour

- .github/workflows/upload-to-pypi.yml
- pyproject.toml
GHActions supposed to build and upload both the wheels and  SDist to Pypi failed (timeout after 6 hours) : https://github.com/deepcharles/ruptures/actions/runs/1291048776 failed 
* Instead of using `joerick/cibuildwheel@v1.9.0`, we now use the `cibuildwheel` package directly. It allowed us to get rid of the manual `include` and `exclude` in the matrix for the `build_wheels` job
* As a bonus, now wheels for Python v3.9 on Windows. 
* We explicitly ask not to build wheels 
* for Python v3.10
* for PyPy 
* We manually force a version (and avoid building local wheels, the ones with `0.1.dev1` prefix)
* We added a immediate test of the built wheels (feature offered by `cibuildwheel` via `CIBW_TEST_REQUIRES` and `CIBW_TEST_COMMAND`
* We switch from `actions/checkout@v1` to `actions/checkout@v2` …
> fix: use cibuildwheel package and add tests

- tests/test_costs.py
From time to time, `test_costs_5D_names` fails on `CostMl` because the random signal has a singular covariance matrix. 
When this happens, the test should be skipped. This will not affect coverage since this part of the code is also tested in `test_costs_5D_noisy_names`.
> test: better handling of mahalanobis

- src/ruptures/detection/_detection/ekcpd_pelt_computation.c
- tests/test_detection.py
The C implementation of Pelt (`KernelCPD`) returned different segmentations when applied several times on the same signal (see #145).
This was because in the C code, we were accessing an address outside of the memory bounds of an array (something like `array[-1]` instead of `array[0]`).
I also added a test to verify that `KernelCPD` always returns the same result on the same signal.
> fix: random behaviour of KernelCPD (Pelt)

- .github/workflows/run-test.yml
- src/ruptures/datasets/pw_constant.py
- src/ruptures/datasets/pw_linear.py
- src/ruptures/datasets/pw_normal.py
- src/ruptures/datasets/pw_wavy.py
- src/ruptures/utils/drawbkps.py
- tests/test_datasets.py
This PR fixes an issue occurring while using the signal generation feature of `ruptures` with a random seed. Two runs with the same random seed would not return the same generated signal. 
```python
import ruptures as rpt
signal1, bkps1 = rpt.pw_constant(n_samples=200, n_features=3, n_bkps=3, noise_std=1, seed=1234)
signal2, bkps2 = rpt.pw_constant(n_samples=200, n_features=3, n_bkps=3, noise_std=1, seed=1234)
assert np.isclose(signal1, signal2).all()
assert bkps1 == bkps2
```
> fix(datasets): propagate random seed for consistency

- .github/workflows/upload-to-pypi.yml
As @oboulant explained [here](https://github.com/deepcharles/ruptures/pull/225#issuecomment-1015301852), `cibuildwheel` stopped working recently for some 32 bits setups (see also scikit-learn/scikit-learn#22122).
In this PR, wheels for cp38-manylinux_i686 and cp39-manylinux_i686 are explicitly excluded when uploading to PyPI, as well as the new `musllinux` supported by cibuildwheel (for now).
> ci: skipping wheel building for Linux 32-bit

- .github/workflows/run-test.yml
- .github/workflows/upload-to-pypi.yml
- pyproject.toml
Pytest coverage is useless when testing wheels.
> ci: remove coverage from the wheel testing process

- .pre-commit-config.yaml
- docs/user-guide/datasets/pw_normal.md
This is just a small change in the docs of `pw_normal`. The line `n = 500, 3  # number of samples` is not working.
```Python
import numpy as np
import matplotlib.pylab as plt
import ruptures as rpt
n = 500, 3  # number of samples
n_bkps = 3  # number of change points, noise standart deviation
signal, bkps = rpt.pw_normal(n, n_bkps)
rpt.display(signal, bkps)
```
->
```Python
import numpy as np
import matplotlib.pylab as plt
import ruptures as rpt
n = 500  # number of samples
n_bkps = 3  # number of change points
signal, bkps = rpt.pw_normal(n, n_bkps)
rpt.display(signal, bkps)
```
> docs: pw_normal

- docs/user-guide/detection/pelt.md
The breakpoint variable, 'bkps' was mispelt to 'b' in the line below
`signal, b = rpt.pw_constant(n, dim, n_bkps, noise_std=sigma)`
This resulted in in error when trying to display the true and estimated breakpoints
Also the plotting function has extra brackets and a comma as seen below
`fig, (ax,) = rpt.display(signal, bkps, my_bkps, figsize=(10, 6))`
This resulted in an integer iteration error. The fix(which encoprates the bkps spelling fix as well) is shown below
`fig, ax = rpt.display(signal, bkps, my_bkps, figsize=(10, 6))`
> docs(typo): Fixed syntax errors

- src/ruptures/costs/costl2.py
- tests/test_costs.py
The `min_size` parameter was set to 2 for CostL2 and produced bad segmentations for small signals (see Issue #242).
Now it is set to 1 by default.
> fix(CostL2): set min_size to 1

- pyproject.toml
- setup.cfg
The job that publishes the documentation online raises an error (see below). It seems that some changes `mkdocstrings` are causing this (https://mkdocstrings.github.io/handlers/overview/#about-the-python-handlers).
```
Run mkdocs build
INFO     -  [macros] - Macros arguments: {'module_name': 'mkdocs_macros', 'modules': [], 'include_dir': '', 'include_yaml': [], 'j2_block_start_string': '', 'j2_block_end_string': '', 'j2_variable_start_string': '', 'j2_variable_end_string': '', 'on_undefined': 'keep', 'on_error_fail': False, 'verbose': False}
INFO     -  [macros] - Found local Python module 'mkdocs_macros' in: /home/runner/work/ruptures/ruptures
INFO     -  [macros] - Found external Python module 'mkdocs_macros' in: /home/runner/work/ruptures/ruptures
INFO     -  [macros] - Extra filters …
```
> ci(docs): fix the doc publishing job

- .github/workflows/run-test.yml
- .pre-commit-config.yaml
- src/ruptures/detection/binseg.py
- src/ruptures/detection/kernelcpd.py
- src/ruptures/detection/pelt.py
- src/ruptures/detection/window.py
- tests/test_costs.py
This PR adds python v3.11 to the matrix for running the tests in the CI. 
pre-commit-ci-update-config has already been merged into ci-py311-wheel branch !
> test: add python v3.11 to test gh action

- .github/workflows/upload-to-pypi.yml
This PR uses by default the latest version of [gh-action-pypi-publish](https://github.com/marketplace/actions/pypi-publish). 
Before this PR, version number `v1.4.1` was pinned in the GH workflow file. It caused the upload part of the job to fail (see [here](https://github.com/deepcharles/ruptures/actions/runs/5199616908/jobs/9377675489)).
> build: use latest gha version for uploading to pypi 

- README.md
Python 3.10 and 3.11 are supported now (there are even wheels on PyPI), so just a trivial update of the `README.md`
> docs: update python version badges in README.md

- mkdocs_macros.py
The links in the documentation to the original notebooks are currently broken. This PR introduces the missing `/` to the links:
[Original link](https://github.com/deepcharles/rupturesblob/master/docs/examples/music-segmentation.ipynb):
```https://github.com/deepcharles/rupturesblob/master/docs/examples/music-segmentation.ipynb```
[New link](https://github.com/deepcharles/ruptures/blob/master/docs/examples/music-segmentation.ipynb):
```https://github.com/deepcharles/ruptures/blob/master/docs/examples/music-segmentation.ipynb```
> docs: fix notebook link in docs

- src/ruptures/detection/bottomup.py
This PR makes some small modifications to improve the speed of the BottomUp segmentation algorithm, especially when applied to long time series.
----
Below is a simple benchmark:
```python
import time
import ruptures as rpt
n_samples, n_dims, sigma = 100_000, 1, 2
n_bkps = 100  # number of breakpoints
signal, bkps = rpt.pw_constant(n_samples, n_dims, n_bkps, noise_std=sigma)
t1 = time.perf_counter(), time.process_time()
algo = rpt.BottomUp(model="normal").fit(signal)
my_bkps = algo.predict(n_bkps=100)
t2 = time.perf_counter(), time.process_time()
print(f" Real time: {t2[0] - t1[0]:.2f} seconds")
print(f" CPU time: {t2[1] - t1[1]:.2f} seconds")
```
**Current implementation**: 46.08 seconds …
> refactor: improve speed of BottomUp

- .github/workflows/run-test.yml
Update the Codecov version from v2 to v4 because Codecoverage actions are currently failing (e.g. https://github.com/deepcharles/ruptures/actions/runs/9305356366/job/25645080125)
> ci(codecov): Update run-test.yml

- .github/workflows/run-test.yml
Updating the GHA that runs tests and uploads to https://app.codecov.io/gh/deepcharles/ruptures 
Now using `codecov/codecov-action@v4` as mentioned in https://github.com/marketplace/actions/checkout
> ci(codecov): update codecov gha version number

- docs/examples/basic-usage.ipynb
- docs/getting-started/basic-usage.ipynb
- docs/javascripts/mathjax.js
- mkdocs.yml
Fix #347 
- changes a few latex delimiters from $ $  to \\( \\) and $$ $$ to \\[ \\].
- change mathjax.js as in [here](https://squidfunk.github.io/mkdocs-material/reference/math/#mathjax)
- fix the unrelated warning about `options` and `selection` in `mkdocs.yml` [(see here)](https://mkdocstrings.github.io/usage/handlers/#selection-options)
> docs: correct Latex formatting

- .github/workflows/check-docs.yml
- .github/workflows/publish-doc-to-remote.yml
- .github/workflows/run-test.yml
- .github/workflows/upload-to-pypi.yml
- README.md
- setup.cfg
An error is thrown when uploading an artefact (`actions/upload-artifact`) because the version is too old
https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/
Everything broke after bumping the version, so I ended up changing more things.
Summary of changes:
- only build wheels for python >=3.8 by modifying `setup.cfg` (there was an error when installing scipy for py37 on win_amd64)
- add wheels for py314 and py314t (whatever this is)
- skip wheels for win32 for py314 and py314t
- update version of `actions/upload-artifact`, and giving a specific name for each artifact to avoid name collision 
- update all possible versions of python and gha (setup-python, checkout, setup-quemu)
- Remove py38 and py314 from tests
My changes are mostly based [on …
> ci(upload-pypi): upgrade version of artefact upload action
